/*
 * @Author: Ramon
 * @Date: 2025-03-31 11:38:44
 * @LastEditTime: 2025-03-31 17:19:18
 * @FilePath: /NIODemo/app/src/test/java/org/example/AppTest.java
 * @Description: 
 */
/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;

import java.nio.ByteBuffer;
import java.nio.channels.FileChannel;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
