/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class demo_opencv_com_opencvdemo2_OpenCvHelper */

#ifndef _Included_demo_opencv_com_opencvdemo2_OpenCvHelper
#define _Included_demo_opencv_com_opencvdemo2_OpenCvHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     demo_opencv_com_opencvdemo2_OpenCvHelper
 * Method:    gray
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_demo_opencv_com_opencvdemo2_OpenCvHelper_gray
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
