/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class demo_opencv_com_opencvdemo2_OpenCvHelper */

#ifndef _Included_demo_opencv_com_opencvdemo2_OpenCvHelper
#define _Included_demo_opencv_com_opencvdemo2_OpenCvHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     demo_opencv_com_opencvdemo2_OpenCvHelper
 * Method:    gray
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_demo_opencv_com_opencvdemo2_OpenCvHelper_gray
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     demo_opencv_com_opencvdemo2_OpenCvHelper
 * Method:    getStringFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_demo_opencv_com_opencvdemo2_OpenCvHelper_getStringFromJni
  (JNIEnv *, jclass);

/*
 * Class:     demo_opencv_com_opencvdemo2_OpenCvHelper
 * Method:    addNum
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_demo_opencv_com_opencvdemo2_OpenCvHelper_addNum
  (JNIEnv *, jobject);

/*
 * Class:     demo_opencv_com_opencvdemo2_OpenCvHelper
 * Method:    accessStaticField
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_demo_opencv_com_opencvdemo2_OpenCvHelper_accessStaticField
  (JNIEnv *, jobject);

/*
 * Class:     demo_opencv_com_opencvdemo2_OpenCvHelper
 * Method:    accessPrivateField
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_demo_opencv_com_opencvdemo2_OpenCvHelper_accessPrivateField
  (JNIEnv *, jobject);

/*
 * Class:     demo_opencv_com_opencvdemo2_OpenCvHelper
 * Method:    accessPublicMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_demo_opencv_com_opencvdemo2_OpenCvHelper_accessPublicMethod
  (JNIEnv *, jobject);

/*
 * Class:     demo_opencv_com_opencvdemo2_OpenCvHelper
 * Method:    accessStaticMethod
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_demo_opencv_com_opencvdemo2_OpenCvHelper_accessStaticMethod
  (JNIEnv *, jobject);

/*
 * Class:     demo_opencv_com_opencvdemo2_OpenCvHelper
 * Method:    accessSuperMethod
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_demo_opencv_com_opencvdemo2_OpenCvHelper_accessSuperMethod
  (JNIEnv *, jobject);

/*
 * Class:     demo_opencv_com_opencvdemo2_OpenCvHelper
 * Method:    intArrayMethod
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_demo_opencv_com_opencvdemo2_OpenCvHelper_intArrayMethod
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     demo_opencv_com_opencvdemo2_OpenCvHelper
 * Method:    objectMethod
 * Signature: (Ldemo/opencv/com/opencvdemo2/Person;)Ldemo/opencv/com/opencvdemo2/Person;
 */
JNIEXPORT jobject JNICALL Java_demo_opencv_com_opencvdemo2_OpenCvHelper_objectMethod
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
