/*
 * @Author: Ramon
 * @Date: 2025-03-31 08:43:30
 * @LastEditTime: 2025-03-31 11:47:06
 * @FilePath: /Algorithm/app/src/main/java/org/example/App.java
 * @Description: 
 */
/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
